// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwnOt_YMdLcUADwSLEHbJVgFxfjZmDKQ',
    appId: '1:803132658202:web:5ae09a028a276067d577a3',
    messagingSenderId: '803132658202',
    projectId: 'fir-tester-9e30b',
    authDomain: 'fir-tester-9e30b.firebaseapp.com',
    storageBucket: 'fir-tester-9e30b.appspot.com',
    measurementId: 'G-PZFZDC0DDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVjp_icdLeH6A0QgjUvDIKfjKsHfZnmOw',
    appId: '1:803132658202:android:8e139cf1d842b68fd577a3',
    messagingSenderId: '803132658202',
    projectId: 'fir-tester-9e30b',
    storageBucket: 'fir-tester-9e30b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeWxYh5bCDF2ZNgeIg5hm2Z0E_2PFMrzk',
    appId: '1:803132658202:ios:4aaf566dfc826556d577a3',
    messagingSenderId: '803132658202',
    projectId: 'fir-tester-9e30b',
    storageBucket: 'fir-tester-9e30b.appspot.com',
    iosClientId: '803132658202-b3pe56d2qarack1acnkfqpo7n2fuiuag.apps.googleusercontent.com',
    iosBundleId: 'com.example.firetester',
  );
}
